# Generated by Django 3.1.7 on 2021-04-06 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategoryMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('relationship', 'Relationship'), ('communication', 'Communication'), ('management', 'Management'), ('analytical', 'Analytical'), ('creative', 'Creative'), ('technical', 'Technical')], max_length=13)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.customuser'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skillcategorymixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.skillcategorymixin')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('profiles.skillcategorymixin',),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profile', to='profiles.Skill'),
        ),
    ]
