# Generated by Django 3.1.7 on 2021-04-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210407_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembershiprequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=8),
        ),
    ]
