# Generated by Django 3.1.7 on 2021-04-07 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210406_1010'),
        ('projects', '0006_auto_20210407_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ownner', to='profiles.userprofile'),
            preserve_default=False,
        ),
    ]
