# Generated by Django 3.1.7 on 2021-04-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectmembershiprequest_status'),
        ('projects', '0007_project_owner'),
    ]

    operations = [
    ]
