# Generated by Django 3.1.7 on 2021-04-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210406_1010'),
        ('projects', '0008_auto_20210407_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_owned', to='profiles.userprofile'),
        ),
    ]
