# Generated by Django 3.1.7 on 2021-04-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210407_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembershiprequest',
            name='responded',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
