# Generated by Django 3.1.7 on 2021-04-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectmembershiprequest_responded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembershiprequest',
            name='responded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
