# Generated by Django 3.1.7 on 2021-04-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210407_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='roles',
            field=models.ManyToManyField(through='projects.ProjectMembership', to='projects.Role'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='projects.role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmembershiprequest',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='projects.role'),
            preserve_default=False,
        ),
    ]
