# Generated by Django 3.1.7 on 2021-04-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210408_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembershiprequest',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='projects.role'),
        ),
    ]
