# Generated by Django 3.1.7 on 2021-04-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20210408_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmembership',
            name='invite_reason',
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='message',
            field=models.TextField(max_length=64, null=True),
        ),
    ]
